# -*- coding: utf-8 -*-
"""
Created on Fri Feb  9 12:27:53 2018

@author: raghuramkowdeed
"""

import pandas as pd
import numpy as np
 

def get_signal_names():
    names = [ 'absacc',
              'acc',
              'aeavol',
              'age',
              'baspread',
              'beta',
              'betasq',
              'bm',
              'bm_ia',
              'cash',
              'cashdebt',
              'cashpr',
              'cfp',
              'cfp_ia',
              'chatoia',
              'chcsho',
              'chempia',
              'chfeps',
              'chinv',
              'chmom',
              'chnanalyst',
              'chpmia',
              'chtx',
              'cinvest',
              'convind',
              'currat',
              'depr',
              'disp',
              'divi',
              'orgcap',
              'pchcapx_ia',
              'pchcurrat',
              'pchdepr',
              'pchgm_pchsale',
              'pchquick',
              'pchsale_pchinvt',
              'pchsale_pchxsga',
              'pchsaleinv',
              'pctacc',
              'pricedelay',
              'ps',
              'divo',
              'dolvol',
              'dy',
              'ear',
              'egr',
              'ep',
              'fgr5yr',
              'gma',
              'grcapx',
              'grltnoa',
              'herf',
              'hire',
              'idiovol',
              'ill',
              'indmom',
              'invest',
              'ipo',
              'lev',
              'lgr',
              'maxret',
              'mom12m',
              'mom1m',
              'mom36m',
              'mom6m',
              'ms',
              'mve',
              'mve_ia',
              'nanalyst',
              'nincr',
              'operprof',
              'roeq',
              'roic',
              'rsup',
              'salecash',
              'saleinv',
              'salerec',
              'secured',
              'securedind',
              'sfe',
              'sgr',
              'sin',
              'sp',
              'std_dolvol',
              'quick',
              'rd',
              'rd_mve',
              'rd_sale',
              'realestate',
              'retvol',
              'roaq',
              'roavol',
              'std_turn',
              'stdacc',
              'stdcf',
              'sue',
              'tang',
              'tb',
              'turn',
              'zerotrade'
            ]
            
    return names